"""first push supabase

Revision ID: 090bcab47c3f
Revises: 
Create Date: 2024-02-16 23:18:47.949723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '090bcab47c3f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('animal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('species', sa.String(length=100), nullable=False),
    sa.Column('binomial_name', sa.String(length=100), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=100), nullable=False),
    sa.Column('food', sa.String(length=100), nullable=False),
    sa.Column('diet_category', sa.String(length=100), nullable=False),
    sa.Column('animal_class', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee')
    op.drop_table('animal')
    # ### end Alembic commands ###
