"""fix error type

Revision ID: a621177e0aaf
Revises: 090bcab47c3f
Create Date: 2024-02-17 01:52:24.303835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a621177e0aaf'
down_revision = '090bcab47c3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.String(length=100),
               type_=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
